#pragma once
#include "Entity.h"
#include "TileMap.h"

#define PLAYER_FRAME_SIZE		32

#define PLAYER_PHYSICAL_WIDTH   12
#define PLAYER_PHYSICAL_HEIGHT  28

#define PLAYER_SPEED            2

#define PLAYER_JUMP_FORCE       10

#define PLAYER_JUMP_DELAY       2

#define PLAYER_LEVITATING_SPEED 4

#define GRAVITY_FORCE           1

enum class State { IDLE, WALKING, JUMPING, FALLING, CLIMBING, DEAD };
enum class Look { RIGHT, LEFT };

enum class PlayerAnim {
	IDLE_LEFT, IDLE_RIGHT, IDLE_BACK,
	WALKING_LEFT, WALKING_RIGHT, 
	JUMPING_LEFT, JUMPING_RIGHT, 
	CROUCHING_LEFT, CROUCHING_RIGHT,
	CLIMBING_TOP_LEFT, CLIMBING_TOP_RIGHT,
	CLIMBING_BOTTOM_LEFT, CLIMBING_BOTTOM_RIGHT,
	RECEIVING_DAMAGE, DEATH,
	SHIELD_IDLE_LEFT, SHIELD_IDLE_RIGHT,
	SHIELD_WALKING_LEFT, SHIELD_WALKING_RIGHT,
	SHIELD_JUMPING_LEFT, SHIELD_JUMPING_RIGHT,
	SHIELD_CLIMBING_TOP_LEFT, SHIELD_CLIMBING_TOP_RIGHT,
	SHIELD_CLIMBING_BOTTOM_LEFT, SHIELD_CLIMBING_BOTTOM_RIGHT


};